parser: '@typescript-eslint/parser'

env:
  browser: true
  es2017: true
  node: true
  mocha: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:prettier/recommended

parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  eqeqeq: [error, allow-null]
  prefer-const: error
  no-undef: off
  no-unused-vars: off
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/explicit-module-boundary-types': off
  'react/prop-types': off
  'react-hooks/rules-of-hooks': error
  'react-hooks/exhaustive-deps': warn

plugins:
  - react
  - react-hooks

settings:
  react:
    version: detect

overrides:
  - files: ['*.js']
    rules:
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/explicit-function-return-type': off
